In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
data=pd.read_csv('Password_data.csv')

In [4]:
data.head()

password strength Unnamed: 2 Unnamed: 3  Unnamed: 4 Unnamed: 5  \
0     kzde5577        1        NaN        NaN         NaN        NaN   
1     kino3434        1        NaN        NaN         NaN        NaN   
2    visi7k1yr        1        NaN        NaN         NaN        NaN   
3     megzy123        1        NaN        NaN         NaN        NaN   
4  lamborghin1        1        NaN        NaN         NaN        NaN   

   Unnamed: 6  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN

In [5]:
data.rename({"Unnamed: 2":"a"}, axis="columns", inplace=True)

        # Then, drop the column as usual.

data.drop(["a"], axis=1, inplace=True)

In [6]:
data.head()

password strength Unnamed: 3  Unnamed: 4 Unnamed: 5  Unnamed: 6
0     kzde5577        1        NaN         NaN        NaN         NaN
1     kino3434        1        NaN         NaN        NaN         NaN
2    visi7k1yr        1        NaN         NaN        NaN         NaN
3     megzy123        1        NaN         NaN        NaN         NaN
4  lamborghin1        1        NaN         NaN        NaN         NaN

In [7]:
 data.rename({"Unnamed: 3":"b"}, axis="columns", inplace=True)

        # Then, drop the column as usual.

data.drop(["b"], axis=1, inplace=True)

In [8]:
 data.rename({"Unnamed: 4":"c"}, axis="columns", inplace=True)

        # Then, drop the column as usual.
data.drop(["c"], axis=1, inplace=True)

In [9]:
 data.rename({"Unnamed: 5":"d"}, axis="columns", inplace=True)

        # Then, drop the column as usual.

data.drop(["d"], axis=1, inplace=True)

In [10]:
 data.rename({"Unnamed: 6":"e"}, axis="columns", inplace=True)

        # Then, drop the column as usual.

data.drop(["e"], axis=1, inplace=True)

In [11]:
data.head()

password strength
0     kzde5577        1
1     kino3434        1
2    visi7k1yr        1
3     megzy123        1
4  lamborghin1        1

In [12]:
data['strength'].unique()

array(['1', '2', '0', 'selim_syl1905@hotmail.com',
       'delioreanxs@hotmail.com', 'mt2gurur@hotmail.com',
       'facebookselim4@hotmail.com', 'anakonda_252@hotmail.com',
       'mamedov.kenan@mail.ru', 'destek@migmedya.com',
       'elitebank44@gmail.com', 'memleketim.info@gmail.com',
       'canersastim@gmail.com', 'arifselim.ask@gmail.com',
       'octoberwind@mynet.com', 'sado_370@hotmail.com',
       'djexploit@gmail.com', 'bursabursa2@hotmail.com',
       'info@kayimoglu.com', 'drselimcelik@gmail.com',
       'bykudelfa@hotmail.com', 'kralkotsk@mynet.com',
       'mnyk12@hotmail.com', 'elitebilgisayar26@gmail.com',
       'elumre@gmail.com', 'selim.ozmen07@hotmail.com',
       'selimkaratas@windowslive.com', 'crazy_boeing@yahoo.com',
       'imkbticaretmeslek@gmail.com', 'mrcds.grmnt@yahoo.com',
       'mert_kaya09@hotmail.com', 'beratmisimi1@gmail.com',
       'cousto@live.com', 'boystreet04@gmail.com',
       'hackerbbqueen15@hotmail.com', 'brkyc3@hotmail.com',
       'bursa

In [13]:
data.isna().sum()

password    1
strength    0
dtype: int64

In [14]:
data[data['password'].isnull()]

password strength
367718      NaN        0

In [15]:
data.dropna(inplace=True)

In [16]:
data.isnull().sum()

password    0
strength    0
dtype: int64

In [17]:
password_array= np.array(data)
print(password_array)

[['kzde5577' '1']
 ['kino3434' '1']
 ['visi7k1yr' '1']
 ...
 ['184520socram' '1']
 ['marken22a' '1']
 ['fxx4pw4g' '1']]


In [18]:
import random
random.shuffle(password_array)

In [19]:
x=[labels[0] for labels in password_array]
y=[labels[1] for labels in password_array]

In [20]:
def word_divide_char(inputs):
    character=[]
    for i in inputs:
        character.append(i)
    return character

In [21]:
word_divide_char('Sam')

['S', 'a', 'm']

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
vectorizer= TfidfVectorizer(tokenizer=word_divide_char)

In [24]:
X= vectorizer.fit_transform(x)

In [25]:
X.shape

(669878, 130)

In [26]:
vectorizer.get_feature_names()

['\x05',
 '\x06',
 '\x08',
 '\x0f',
 '\x10',
 '\x12',
 '\x13',
 '\x16',
 '\x17',
 '\x18',
 '\x19',
 '\x1b',
 '\x1c',
 '\x1d',
 '\x1e',
 ' ',
 '!',
 '"',
 '#',
 '$',
 '%',
 '&',
 '(',
 ')',
 '*',
 '+',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '{',
 '|',
 '}',
 '~',
 '\x7f',
 '\xa0',
 '¡',
 '¦',
 '¨',
 '«',
 '°',
 '±',
 '²',
 '³',
 '´',
 'µ',
 '¶',
 '·',
 '¹',
 'º',
 '½',
 '¾',
 '¿',
 'ß',
 'à',
 'á',
 'â',
 'ä',
 'å',
 'æ',
 'ç',
 'è',
 'é',
 'ê',
 'ï',
 'ð',
 'ñ',
 'ò',
 'ó',
 'ô',
 'õ',
 'ö',
 '÷',
 'ù',
 'ú',
 'û',
 'ü',
 'ý',
 'þ',
 'ÿ',
 '‚',
 '›',
 '™']

In [27]:
first_document_vector=X[0]
print(first_document_vector)

  (0, 61)	0.29172781428761324
  (0, 76)	0.33586416303344585
  (0, 54)	0.28560889593988636
  (0, 55)	0.22110365463256748
  (0, 34)	0.5673406272215817
  (0, 36)	0.5914012948352062


In [28]:
first_document_vector.T.todense()

matrix([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.56734063],
        [0.        ],
        [0.59140129],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0

In [29]:
df=pd.DataFrame(first_document_vector.T.todense(),index=vectorizer.get_feature_names(),columns=['TF-IDF'])

In [30]:
df.sort_values(by=['TF-IDF'],ascending=False)

TF-IDF
7   0.591401
5   0.567341
z   0.335864
k   0.291728
d   0.285609
e   0.221104
²   0.000000
«   0.000000
°   0.000000
±   0.000000
   0.000000
³   0.000000
¦   0.000000
´   0.000000
µ   0.000000
¶   0.000000
·   0.000000
¹   0.000000
¨   0.000000
   0.000000
¡   0.000000
    0.000000
~   0.000000
}   0.000000
|   0.000000
{   0.000000
y   0.000000
x   0.000000
w   0.000000
v   0.000000
..       ...
3   0.000000
4   0.000000
   0.000000
n   0.000000
m   0.000000
l   0.000000
j   0.000000
i   0.000000
h   0.000000
g   0.000000
f   0.000000
c   0.000000
b   0.000000
a   0.000000
`   0.000000
_   0.000000
^   0.000000
]   0.000000
\   0.000000
[   0.000000
@   0.000000
?   0.000000
>   0.000000
=   0.000000
<   0.000000
;   0.000000
9   0.000000
8   0.000000
6   0.000000
™   0.000000

[130 rows x 1 columns]

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.25)

In [33]:
X_train.shape

(502408, 130)

In [34]:
from sklearn.linear_model import LogisticRegression

In [35]:
clf=LogisticRegression(random_state=0,multi_class='multinomial',solver='lbfgs')

In [36]:
clf.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=1, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [37]:
dt=np.array(['marken22a'])
prediction=vectorizer.transform(dt)
clf.predict(prediction)

array(['1'], dtype='<U32')

In [38]:
y_pred=clf.predict(X_test)
y_pred

array(['1', '1', '1', ..., '1', '1', '0'], dtype='<U32')

In [39]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [40]:
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[  6661  15925      7 ...      0      0      0]
 [  4914 115804   3220 ...      0      0      0]
 [    33   6502  14345 ...      0      0      0]
 ...
 [     2      0      0 ...      0      0      0]
 [     2      0      0 ...      0      0      0]
 [     1      0      0 ...      0      0      0]]
0.8169224338687526


In [51]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                                  precision    recall  f1-score   support

                               0       0.57      0.29      0.39     22593
                               1       0.84      0.93      0.88    123938
                               2       0.82      0.69      0.75     20880
        anakonda_252@hotmail.com       0.00      0.00      0.00         1
           antit0xin@hotmail.com       0.00      0.00      0.00         1
             axiselo@hotmail.com       0.00      0.00      0.00         1
          beratmisimi1@gmail.com       0.00      0.00      0.00         2
           boskartus@hotmail.com       0.00      0.00      0.00         1
           boystreet04@gmail.com       0.00      0.00      0.00         1
   carizma_cocuk1987@hotmail.com       0.00      0.00      0.00         1
                 cousto@live.com       0.00      0.00      0.00         1
          crazy_boeing@yahoo.com       0.00      0.00      0.00         1
         delioreanxs@hotmail.com     